[package]
name = "parsley-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos="0.12.0"
parsley = { path = "../parsley" }
lazy_static = "1.4.0"
